- name: ky-auditing | Getting logging installation files
  copy:
    src: "fluentbit-operator"
    dest: "{{ kylincloud_dir }}/"


- name: ky-auditing | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kylincloud_dir }}/fluentbit-operator/{{ item.file }}"
  with_items:
    - { name: custom-output-elasticsearch-auditing, file: custom-output-elasticsearch-auditing.yaml }

- name: ky-auditing | Apply fluentbit operator custom resources
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ kylincloud_dir }}/fluentbit-operator