apiVersion: v1
kind: Service
metadata:
  name: kylincloud-router-gateway
  labels:
    app: kylincloud
    component: ks-router
    tier: backend
spec:
  selector:
    app: kylincloud
    component: ks-router
    tier: backend
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

