---
- name: KylinCloud | Setting images' namespace override
  set_fact:
    namespace_override: "kylincloudio"
  when: (local_registry is defined and local_registry == "registry.cn-beijing.aliyuncs.com") or (zone is defined and zone == "cn")

- name: KylinCloud | Configuring defaults
  debug:
    msg: "Check roles/kylincloud-defaults/defaults/main.yml"
  tags:
    - always
