apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kylincloud-node-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kylincloud-node-exporter
subjects:
- kind: ServiceAccount
  name: node-exporter
  namespace: kylincloud-monitoring-system
