apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
    app.kubernetes.io/vendor: kylincloud
  name: prometheus
  namespace: kylincloud-monitoring-system
spec:
  endpoints:
  - interval: 1m
    port: web
    relabelings:
    - action: labeldrop
      regex: (service|endpoint)
  selector:
    matchLabels:
      prometheus: k8s
