---

- name: ky-events | Getting ky-events installation files
  copy:
    src: "kube-events"
    dest: "{{ kylincloud_dir }}/ky-events/"

- name: ky-events | Getting ky-events installation files
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kylincloud_dir }}/{{ item.path }}/{{ item.file }}"
  with_items:
    - { path: ky-events, file: custom-values-events.yaml }

- name: ky-events | Checking ky-events
  shell: >
    {{ bin_dir }}/helm list -f ky-events -n kylincloud-logging-system
  register: events_check
  failed_when: false

- name: ky-events | Checking ky-events
  shell: >
    {{ bin_dir }}/kubectl -n kylincloud-logging-system get rulers.events.kylincloud.io ky-events-ruler -o jsonpath='{.spec.image}'
  register: events_ruler_check
  when:
    - (events_check.stdout.find("deployed") != -1) and (events_check.stdout.find("0.1.0") != -1)
  failed_when: false

- name: ky-events | Deploying ky-events
  shell: >
    {{ bin_dir }}/helm upgrade --install ky-events
    {{ kylincloud_dir }}/ky-events/kube-events
    -f {{ kylincloud_dir }}/ky-events/custom-values-events.yaml
    -n kylincloud-logging-system
    --force
  register: deploy_result
  until: deploy_result is succeeded
  retries: 3
  delay: 10
  when:
    - (events_check.stdout.find("deployed") == -1) or (events_check.stdout.find("0.1.0") == -1) or (events_ruler_check.stdout.find("v0.1.0") != -1)


- import_tasks: fluentbit-operator.yaml


- name: ky-events | Importing ky-events status
  shell: >
    {{ bin_dir }}/kubectl patch cc ks-installer
    --type merge
    -p '{"status": {"events": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}'
    -n kylincloud-system
  register: import
  failed_when: "import.stderr and 'Warning' not in import.stderr"
  until: import is succeeded
  retries: 5
  delay: 3


- name: ky-events | Importing ky-events status
  shell: >
    {{ bin_dir }}/kubectl patch cc ks-installer
    --type merge
    -p '{"status": {"events": {"ruler": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}}'
    -n kylincloud-system
  register: import
  failed_when: "import.stderr and 'Warning' not in import.stderr"
  until: import is succeeded
  retries: 5
  delay: 3
  when:
    - events is defined
    - events.ruler is defined
    - events.ruler.enabled is defined
    - events.ruler.enabled == True
