apiVersion: logging.kylincloud.io/v1alpha2
kind: Input
metadata:
  name: tail
  namespace: kylincloud-logging-system
  labels:
    logging.kylincloud.io/enabled: "true"
    logging.kylincloud.io/component: "logging"
spec:
  tail:
    tag: kube.*
    path: /var/log/containers/*.log
    parser: docker
    refreshIntervalSeconds: 10
    memBufLimit: 5MB
    skipLongLines: true
    db: /fluent-bit/tail/pos.db
    dbSync: Normal
    excludePath: /var/log/containers/*_kylincloud-logging-system_events-exporter*.log,/var/log/containers/kube-auditing-webhook*_kylincloud-logging-system_kube-auditing-webhook*.log

