apiVersion: logging.kylincloud.io/v1alpha2
kind: Filter
metadata:
  labels:
    logging.kylincloud.io/enabled: 'true'
    logging.kylincloud.io/component: "auditing"
  name: filter-auditing
  namespace: kylincloud-logging-system
spec:
  filters:
    - parser:
        keyName: log
        parser: json
    - modify:
        conditions:
          - keyDoesNotExist:
              AuditID: ''
        rules:
          - add:
              ignore: 'true'
    - modify:
        rules:
          - remove: Trace
    - grep:
        exclude: ignore true
  match: kube_auditing

