---

- name: KylinCloud | Getting KylinCloud component version
  shell: >
    {{ bin_dir }}/helm 2to3 convert {{ item }}
  loop:
    - "ky-openldap"
    - "ky-redis"
    - "ky-minio"
    - "ky-openpitrix"
    - "elasticsearch-logging"
    - "elasticsearch-logging-curator"
    - "istio"
    - "istio-init"
    - "jaeger-operator"
    - "ky-jenkins"
    - "ky-sonarqube"
    - "logging-fluentbit-operator"
    - "uc"
    - "metrics-server"
  failed_when: false