apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kylincloud-custom-metrics-server-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kylincloud-custom-metrics-server-resources
subjects:
- kind: ServiceAccount
  name: prometheus-adapter
  namespace: kylincloud-monitoring-system
