- name: KylinCloud | Getting minio installation files
  copy:
    src: "{{ item }}"
    dest: "{{ kylincloud_dir }}/"
  loop:
    - "minio-ha"


- name: KylinCloud | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kylincloud_dir }}/{{ item.file }}"
  with_items:
    - { name: custom-values-minio, file: custom-values-minio.yaml }


- name: KylinCloud | Checking minio
  shell: >
    {{ bin_dir }}/helm list -n kylincloud-system | grep "ky-minio"
  register: minio_check
  failed_when: false


- block:
    - name: KylinCloud | Deploying minio
      shell: >
        {{ bin_dir }}/helm upgrade --install ky-minio
        {{ kylincloud_dir }}/minio-ha
        -f {{ kylincloud_dir }}/custom-values-minio.yaml
        --set fullnameOverride=minio
        --namespace kylincloud-system
        --wait --timeout 1800s
      register: minio_status
      failed_when: false


    - debug:
        msg:
         - 1. check the storage configuration and storage server
         - 2. make sure the DNS address in /etc/resolv.conf is available
         - 3. execute 'kubectl logs -n kylincloud-system -l job-name=minio-make-bucket-job' to watch logs
         - 4. execute 'helm -n kylincloud-system uninstall ky-minio && kubectl -n kylincloud-system delete job minio-make-bucket-job'
         - 5. Restart the installer pod in kylincloud-system namespace
      when: minio_status.rc != 0


    - fail:
        msg: "It is suggested to refer to the above methods for troubleshooting problems ."
      when: minio_status.rc != 0
  when:
    - (minio_check.stdout.find("deployed") == -1) or (minio_check.stdout.find("RELEASE.2019-08-07T01-59-21Z") == -1)


- name: KylinCloud | Importing minio status
  shell: >
    {{ bin_dir }}/kubectl patch cc ky-installer
    --type merge
    -p '{"status": {"minio": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}'
    -n kylincloud-system
  register: import
  failed_when: "import.stderr and 'Warning' not in import.stderr"
  until: import is succeeded
  retries: 5
  delay: 3