
- name: KylinCloud | Creating redis migration script
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kylincloud_dir }}/{{ item.file }}"
  with_items:
    - { path: /etc/kylincloud, file: redisMigrate.py }


- name: KylinCloud | Checking redis-ha status
  shell: >
    {{ bin_dir }}/kubectl get pod -n kylincloud-system | grep 'redis-ha' | grep -v 'Running' | wc -l
  register: import
  until: import.stdout == "0"
  retries: 30
  delay: 30


- name: ky-logging | Migrating redis data
  shell: >
    chmod +x {{ kylincloud_dir }}/redisMigrate.py &&
    {{ kylincloud_dir }}/redisMigrate.py


- name: KylinCloud | Disabling old redis
  shell: >
    {{ bin_dir }}/kubectl -n kylincloud-system scale deployment redis --replicas=0