---

- hosts: localhost
  gather_facts: false
  roles:
    - kylincloud-defaults
    - role: ky-logging
      when:
        - "status.logging is not defined or status.logging.status is not defined or status.logging.status != 'enabled'"