---

- hosts: localhost
  gather_facts: false
  roles:
    - kylincloud-defaults
    - role: metrics-server
      when:
        - "metrics_server is defined and metrics_server.enabled == true"
        - "status.metricsServer is not defined or status.metricsServer.status is not defined or status.metricsServer.status != 'enabled'"
