---

- hosts: localhost
  gather_facts: false
  roles:
    - kylincloud-defaults
    - role: openpitrix
      when:
        - openpitrix is defined
        - openpitrix.store is defined
        - openpitrix.store.enabled is defined
        - openpitrix.store.enabled