---

- hosts: localhost
  gather_facts: false
  roles:
    - kylincloud-defaults
    - role: ky-istio
      when:
        - "status.servicemesh is not defined or status.servicemesh.status is not defined or status.servicemesh.status != 'enabled'"