---
- name: KylinCloud | Creating KylinCloud directory
  file:
    path: "{{ kylincloud_dir }}"
    state: directory
    mode: 0755


- name: KylinCloud | Getting installation init files
  copy:
    src: "{{ item }}"
    dest: "{{ kylincloud_dir }}/"
  loop:
    - "jwt-script"


# https://tools.ietf.org/html/rfc7518#section-3.2
# A key of the same size as the hash output (for instance, 256 bits for"HS256") or larger MUST be used with this algorithm.
- name: KylinCloud | Creating KylinCloud Secret
  shell: >
    dd if=/dev/urandom bs=128 count=1 2>/dev/null | base64 | tr -d "=+/" | tr -d '\n' | dd bs=32 count=1 2>/dev/null
  register: ks_secret


- name: KylinCloud | Creating KylinCloud Secret
  set_fact:
    ks_secret_str: "{{ ks_secret.stdout }}"
  when:
    - (authentication is not defined and authentication.jwtSecret is not defined) or authentication.jwtSecret == ""


- name: KylinCloud | Creating KylinCloud Secret
  set_fact:
    ks_secret_str: "{{ authentication.jwtSecret }}"
  when:
    - authentication is defined and authentication.jwtSecret is defined and authentication.jwtSecret != ""


- name: KylinCloud | Enabling Token Script
  file:
    path: "{{ kylincloud_dir }}/jwt-script/jwt.sh"
    mode: 0755


- name: KylinCloud | Getting KylinCloud Token
  shell: >
    /bin/bash {{ kylincloud_dir }}/jwt-script/jwt.sh  {{ ks_secret_str }} '{"email": "admin@kylincloud.io","username": "admin","token_type": "static_token"}'
  register: ks_token


- name: KylinCloud | Checking KylinCloud secrets
  shell: >
    {{ bin_dir }}/kubectl get secrets -n kylincloud-system
  register: kylincloud_secrets

- name: KylinCloud | Deleting KylinCloud secret
  shell: >
    {{ bin_dir }}/kubectl delete secrets -n kylincloud-system kylincloud-secret
  when:
    - kylincloud_secrets.stdout.find("kylincloud-secret") != -1
    - authentication is defined and authentication.jwtSecret is defined and authentication.jwtSecret != ""

- name: KylinCloud | Creating components token
  shell: >
    {{ bin_dir }}/kubectl create secret generic kylincloud-secret
    --from-literal=token={{ ks_token.stdout }}
    --from-literal=secret={{ ks_secret_str }}
    -n kylincloud-system
  register: secret_status
  failed_when: "secret_status.stderr and 'AlreadyExists' not in secret_status.stderr"
